# Generated by Django 2.0.2 on 2018-08-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180814_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='images',
            new_name='image',
        ),
    ]
